---
title: "Examining the relationship between Neighbourhood Crime Rate and Demographic Data in Toronto’s 140 historical neighbourhoods in 2016"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
always_allow_html: true
---

# Project Description

This research study aims to explore the relationship between crime rate and the characteristics of neighbourhoods in Toronto in 2016. Past studies showed that neighbourhood characteristics were significant factors of the crime rate of an area (Foster et.al 2010). These characteristics include: social-economic factors such as number of businesses, number of community spaces such as parks, green spaces and community centers, ease of transit access, and human factors such as community belonging and quality of local communities (Statistics Canada 2021). In this study, we aim to explore the relationship between the demographics, neighbourhood amenities and crime rate of neighbourhoods. Understanding this relationship will help the government and local communities respond more effectively against emerging crime rates, by eliminating risk factors and improving the well-being of a neighbourhood.


# Midterm Report

You can read about my midterm report where the datasets were analysed, and preliminary tests are done to investigate the relationships of crime rate in Toronto neighbourhoods and their demographic characteristics.

# Interactive Visualizations

There are several interactive visualizations which help you familiarize with the trends and distributions of Toronto's crime rates. 

# Final Report

Based on the "Next Steps" in the Midterm Report, new datasets are included into my analysis on what factors affect crime rates in Toronto neighbourhoods, as well as machine learning models which predict how crime rates change as different parameters of neighbourhoods are modified and adjusted. 

[PDF Download](https://github.com/Tyler-CY/JSC370-Final/blob/master/Toronto%20Neighbourhood%20Crime%20HTML%20PDF%20version.pdf)
